AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal EC2 for artifact deploy (SG + EC2 + Public IP)

Parameters:
  StackName:
    Type: String
    Default: gha-ec2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t3.micro
  AppPort:
    Type: Number
    Default: 5000
  YourIpCidr:
    Type: String
    Default: 0.0.0.0/0
  AmiId:                           # <-- new
    Type: AWS::EC2::Image::Id      # <-- plain AMI id

Resources:
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${StackName} SG"
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: !Ref YourIpCidr }
        - { IpProtocol: tcp, FromPort: !Ref AppPort, ToPort: !Ref AppPort, CidrIp: 0.0.0.0/0 }

  AppEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId           # <-- changed
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: [ !Ref AppSG ]
      Tags: [{ Key: Name, Value: !Ref StackName }]


Outputs:
  PublicIp:
    Value: !GetAtt AppEC2.PublicIp
  InstanceId:
    Value: !Ref AppEC2
  SecurityGroupId:
    Value: !Ref AppSG
