AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal EC2 for artifact deploy (SG + EC2 + Public IP)

Parameters:
  StackName:
    Type: String
    Default: gha-ec2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 key pair name (keep it in GitHub Secrets)
  InstanceType:
    Type: String
    Default: t3.micro
  AppPort:
    Type: Number
    Default: 5000
  YourIpCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR allowed for SSH (use x.x.x.x/32 for your IP)
  AmiParameter:  # Use Amazon Linux 2023 latest (x86_64) via SSM
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${StackName} SG"
      VpcId: !Ref 'AWS::NoValue'  # default VPC
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: !Ref YourIpCidr }
        - { IpProtocol: tcp, FromPort: !Ref AppPort, ToPort: !Ref AppPort, CidrIp: 0.0.0.0/0 }

  AppEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiParameter
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: [ !Ref AppSG ]
      Tags:
        - Key: Name
          Value: !Ref StackName

Outputs:
  PublicIp:
    Value: !GetAtt AppEC2.PublicIp
  InstanceId:
    Value: !Ref AppEC2
  SecurityGroupId:
    Value: !Ref AppSG
