name: EC2 deploy (artifact-based, clean)

on:
  push:
    branches: [main, master]
    paths:
      - hello-ecr/**
      - .github/workflows/deploy-artifactvscript.yml
  workflow_dispatch:

concurrency:
  group: ec2-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_PORT: "5000"
  HEALTH_PATH: "/"
  AWS_REGION: eu-west-1
  EC2_INSTANCE_NAME: gha-terraform-runner
  EC2_AMI_FILTER: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
  EC2_INSTANCE_TYPE: t3.micro
  SG_NAME: gha-ec2-sg
  ASSOCIATE_EIP: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('hello-ecr/requirements.txt') }}
      - name: Build artifact
        run: |
          mkdir -p dist
          tar -czf dist/hello-ecr.tgz -C hello-ecr .
          (cd dist && sha256sum hello-ecr.tgz > hello-ecr.tgz.sha256)
      - uses: actions/upload-artifact@v4
        with:
          name: hello-ecr-artifact
          path: dist/
          compression-level: 0

  ensure_ec2:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      PUBLIC_IP: ${{ steps.out.outputs.PUBLIC_IP }}
      EPH_KEY_NAME: ${{ steps.out.outputs.EPH_KEY_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # optional
          aws-region: ${{ env.AWS_REGION }}
      - name: Ensure EC2 (SG/EIP/AMI/key/instance)
        id: ensure
        env:
          YOUR_IP_CIDR: ${{ secrets.YOUR_IP_CIDR }}
          SG_NAME: ${{ env.SG_NAME }}
          APP_PORT: ${{ env.APP_PORT }}
          EC2_AMI_FILTER: ${{ env.EC2_AMI_FILTER }}
          EC2_INSTANCE_TYPE: ${{ env.EC2_INSTANCE_TYPE }}
          EC2_INSTANCE_NAME: ${{ env.EC2_INSTANCE_NAME }}
          ASSOCIATE_EIP: ${{ env.ASSOCIATE_EIP }}
        run: bash hello-ecr/scripts/ensure_ec2.sh
      - name: Save outputs
        id: out
        run: |
          echo "PUBLIC_IP=${{ steps.ensure.outputs.PUBLIC_IP }}" >> $GITHUB_OUTPUT
          echo "EPH_KEY_NAME=${{ steps.ensure.outputs.EPH_KEY_NAME }}" >> $GITHUB_OUTPUT
      - name: Upload ephemeral key
        uses: actions/upload-artifact@v4
        with:
          name: ephemeral-key
          path: /tmp/key.pem
          retention-days: 1

  deploy:
    needs: [ build, ensure_ec2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: hello-ecr-artifact, path: ./artifact }
      - name: Verify artifact
        run: cd artifact && sha256sum -c hello-ecr.tgz.sha256
      - uses: actions/download-artifact@v4
        with: { name: ephemeral-key, path: ./ssh }
      - name: SSH bootstrap
        run: |
          chmod 600 ./ssh/key.pem
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ needs.ensure_ec2.outputs.PUBLIC_IP }} >> ~/.ssh/known_hosts
          for i in {1..30}; do
            nc -z ${{ needs.ensure_ec2.outputs.PUBLIC_IP }} 22 && break || (echo "waiting for ssh..." && sleep 5)
          done
      - name: Upload & deploy
        env:
          HOST: ${{ needs.ensure_ec2.outputs.PUBLIC_IP }}
        run: |
          scp -i ./ssh/key.pem ./artifact/hello-ecr.tgz ubuntu@$HOST:/home/ubuntu/hello-ecr.tgz
          scp -i ./ssh/key.pem hello-ecr/scripts/deploy_systemd.sh ubuntu@$HOST:/home/ubuntu/deploy_systemd.sh
          ssh -i ./ssh/key.pem ubuntu@$HOST "bash /home/ubuntu/deploy_systemd.sh"

  cleanup:
    if: always()
    needs: [ ensure_ec2, deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # optional
          aws-region: ${{ env.AWS_REGION }}
      - name: Delete ephemeral keypair
        run: |
          KEY="${{ needs.ensure_ec2.outputs.EPH_KEY_NAME }}"
          [ -n "$KEY" ] && aws ec2 delete-key-pair --key-name "$KEY" || true
