name: Build & Push Hello World to ECS-Lambda ECR

on:
  push:
    paths:
      - "hello-ecr/**"
      - ".github/workflows/deploy-hello-ecr.yml"
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 881490114584.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: ecs-lambda
  IMAGE_NAME: hello-world
  DOCKER_CONTEXT: ./hello-ecr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          IMAGE_TAG: hello-${{ github.run_number }}
        run: |
          set -e
          echo "Building Docker image for tag: $IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG $DOCKER_CONTEXT

          FULL_TAG=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          LATEST_TAG=${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

          docker tag $IMAGE_NAME:$IMAGE_TAG $FULL_TAG
          docker tag $IMAGE_NAME:$IMAGE_TAG $LATEST_TAG

          echo "Pushing to $FULL_TAG"
          docker push $FULL_TAG
          docker push $LATEST_TAG

      - name: Print image URIs
        run: |
          echo "✅ Image pushed successfully:"
          echo " - $ECR_REGISTRY/$ECR_REPOSITORY:hello-${{ github.run_number }}"
          echo " - $ECR_REGISTRY/$ECR_REPOSITORY:latest"
